import "https://static.line-scdn.net/liff/edge/2/sdk.js";
// give access to testingFood form trigger.js || modular 
import testingFood from "./trigger.js"

// TEMPLATE FUNCTION TO INITIALIZE LIFF
window.onload = function() {
    const useNodeJS = false;   // if you are not using a node server, set this value to false
    const defaultLiffId = "1655319946-OeEe9ZXR";   // change the default LIFF value if you are not using a node server

    // DO NOT CHANGE THIS
    let myLiffId = "";

    // if node is used, fetch the environment variable and pass it to the LIFF method
    // otherwise, pass defaultLiffId
    if (useNodeJS) {
        fetch('/send-id')
            .then(function(reqResponse) {
                return reqResponse.json();
            })
            .then(function(jsonResponse) {
                myLiffId = jsonResponse.id;
                initializeLiffOrDie(myLiffId);
            })
            .catch(function(error) {
                document.getElementById("liffAppContent").classList.add('hidden');
                document.getElementById("nodeLiffIdErrorMessage").classList.remove('hidden');
            });
    } else {
        myLiffId = defaultLiffId;
        initializeLiffOrDie(myLiffId);
    }

    // buttonClickHandler
    document.querySelector('#getHistoryButton').addEventListener('click', _ => {
        window.alert('Nothing here !!!\nComeback when my head full of idea')
    })

    let spanInner = document.querySelector('#jumlah');

    document.querySelector('#plus').addEventListener('click', _ => {
        spanInner.innerHTML -=- 1
    })

    document.querySelector('#minus').addEventListener('click', _ => {
        spanInner.innerHTML -= 1
    })

    document.querySelector('#getHomeButton').addEventListener('click', e => {
        document.getElementById("homeMenu").style.display = 'block';
        document.querySelector('#addSectionMenuHere').innerHTML = "";
        document.querySelector('#name-items').innerHTML = "";
        document.getElementById("container-profile").classList.add('hidden');
        document.querySelector('#not-login').classList.add('hidden');
        document.querySelector('#chartMenu').classList.add('hidden');
        e.preventDefault()
    })
};

/**
* Check if myLiffId is null. If null do not initiate liff.
* @param {string} myLiffId The LIFF ID of the selected element
*/
function initializeLiffOrDie(myLiffId) {
    if (!myLiffId) {
        document.getElementById("liffAppContent").classList.add('hidden');
        document.getElementById("liffIdErrorMessage").classList.remove('hidden');
    } else {
        initializeLiff(myLiffId);
    }
}

/**
* Initialize LIFF
* @param {string} myLiffId The LIFF ID of the selected element
*/
function initializeLiff(myLiffId) {
    liff
        .init({
            liffId: myLiffId
        })
        .then(() => {
            // start to use LIFF's api
            initializeApp();
        })
        .catch((err) => {
            document.getElementById("liffAppContent").classList.add('hidden');
            document.getElementById("liffInitErrorMessage").classList.remove('hidden');
            console.error(err)
        });
}

/**
 * Initialize the app by calling functions handling individual app components
 */
function initializeApp() {
    // displaying liff user data like username, photo, app version etc
    displayLiffData();
    // call All content 
    testingFood()
    registerButtonHandlers();

    if (liff.isLoggedIn()) {
        document.getElementById('liffLoginButton').disabled = true;
    } else {
        document.getElementById('liffLogoutButton').disabled = true;
    }

}

/**
* Display data generated by invoking LIFF methods
*/
function displayLiffData() {
    document.querySelector('.browserLanguage').textContent = liff.getLanguage();
    if (liff.isInClient() === false) {
        document.querySelector('.lineVersion').textContent = 'You have to login'
    }else{
        document.querySelector('.lineVersion').textContent = liff.getLineVersion();
    }
    
    document.querySelector('.deviceOS').textContent = liff.getOS();
}

/**
* Register event handlers for the buttons displayed in the app
*/
function registerButtonHandlers() {

    // This func for sending message by templat you change it by replace 'text' value by what ever you want
    document.getElementById('sendMessageButton').addEventListener('click', function() {
        if (!liff.isInClient()) {
            window.alert('This features only in app client')
        } else {
            liff.sendMessages([{
                'type': 'text',
                'text': `Berikut Pesanan Anda : ${document.querySelector('#name-items').innerHTML} sejumlah ${spanInner.innerHTML} gelas. Terima Kasih Atas Pesanannya, Mohon Ditunggu`
            }]).then(function() {
                window.alert('Pesanan Terkirim');
            }).catch(function(error) {
                window.alert('Error sending message: ' + error);
            });
        }
    });

    // Open in external browser in case you want do something like via web
    document.getElementById('openWindowButton').addEventListener('click', function() {
        if (!liff.isInClient()) {
            window.alert('This features only on in app Client')
        }else {
            liff.openWindow({
                // change the url value by your liff link 
                url: 'https://liff.line.me/1655319946-OeEe9ZXR',
                external: true
            });
        }
        
    });

    // getting all line user data 
    document.getElementById('getProfileButton').addEventListener('click', function() {
        document.getElementById("homeMenu").style.display = 'none';

        // Check client login or not
        if (!liff.isLoggedIn()) {
            // if not login this section gonna show and block all content
            document.querySelector('#not-login').classList.remove('hidden');
        }

        liff.getProfile().then(function(profile) {
                document.getElementById("container-profile").classList.remove('hidden');
                document.querySelector('.displayNameField').textContent = profile.displayName;

                // took iamge from user line data
                const img = document.querySelector('#profileImage');
                img.src = profile.pictureUrl;
                img.alt = 'Profile Picture';

                document.querySelector('.statusMessageField').textContent = profile.statusMessage;
            }).catch(function(error) {
                console.error('Error getting profile: ' + error);
            });

    });

    // login call, only when external browser is used
    document.getElementById('liffLoginButton').addEventListener('click', function() {
        if (!liff.isLoggedIn()) {
            // set `redirectUri` to redirect the user to a URL other than the front page of your LIFF app.
            liff.login();

        }
    });

    // logout call, when external 
    document.getElementById('liffLogoutButton').addEventListener('click', function() {
        if (liff.isLoggedIn()) {
            if (liff.isInClient()) {
                window.alert('This features only if ur on external window')
            }else{
                liff.logout();
                window.location.reload();
            }
            
        }
    });
}